Create a user search history function
kevinvongmany/beatbrowser pull request #11
Opened 2024-07-13 04:35 UTC by leontran44

Add drop down list and dynamically add value functions

2024-07-13 04:47 UTC, leontran44 commented
ah silly me @kevinvongmany, I tested the code and played around with it and commented out a piece of code that clear out the the existing value when adding the a new value in. So the it will not loop again when add new value
![code](https://github.com/user-attachments/assets/3796eabe-7f00-4655-a275-4dc16f779484)

2024-07-13 05:27 UTC, kevinvongmany requested changes
Just update the source for the script.js and we're good!

2024-07-13 05:27 UTC, kevinvongmany commented on index.html
> +    <script src="script.js"></script>
Could you update line #16 so it's pointing to the new file? Once done, I'll approve this.

2024-07-13 05:58 UTC, kevinvongmany approved these changes

2024-07-15 09:05 UTC, Cbeattie97 approved these changes
Looking good!

2024-07-15 09:05 UTC, merged